export declare function err(prefix: string, ...args: unknown[]): void;
export declare function err(prefix: string, filename: string, ...args: unknown[]): void;
export declare function errWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function errWrite(prefix: string, ...args: unknown[]): void;
export declare function errConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function errConsole(prefix: string, ...args: unknown[]): void;
export declare function sErr(prefix: string, filename: string, ...args: unknown[]): void;
export declare function sErr(prefix: string, ...args: unknown[]): void;
export declare function warn(prefix: string, filename: string, ...args: unknown[]): void;
export declare function warn(prefix: string, ...args: unknown[]): void;
export declare function warnWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function warnWrite(prefix: string, ...args: unknown[]): void;
export declare function warnConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function warnConsole(prefix: string, ...args: unknown[]): void;
export declare function nomal(prefix: string, filename: string, ...args: unknown[]): void;
export declare function nomal(prefix: string, ...args: unknown[]): void;
export declare function nomalWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function nomalWrite(prefix: string, ...args: unknown[]): void;
export declare function nomalConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function nomalConsole(prefix: string, ...args: unknown[]): void;
export declare function info(prefix: string, filename: string, ...args: unknown[]): void;
export declare function info(prefix: string, ...args: unknown[]): void;
export declare function infoWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function infoWrite(prefix: string, ...args: unknown[]): void;
export declare function infoConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function infoConsole(prefix: string, ...args: unknown[]): void;
//# sourceMappingURL=nodelogger.d.ts.map