export declare function err(prefix: string, ...args: unknown[]): void;
export declare function err(prefix: string, filename: string, ...args: unknown[]): void;
export declare function errWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function errWrite(prefix: string, ...args: unknown[]): void;
export declare function errConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function errConsole(prefix: string, ...args: unknown[]): void;
export declare function sErr(prefix: string, filename: string, ...args: unknown[]): string;
export declare function sErr(prefix: string, ...args: unknown[]): string;
export declare function warn(prefix: string, filename: string, ...args: unknown[]): void;
export declare function warn(prefix: string, ...args: unknown[]): void;
export declare function warnWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function warnWrite(prefix: string, ...args: unknown[]): void;
export declare function warnConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function warnConsole(prefix: string, ...args: unknown[]): void;
export declare function sWarn(prefix: string, filename: string, ...args: unknown[]): string;
export declare function sWarn(prefix: string, ...args: unknown[]): string;
export declare function normal(prefix: string, filename: string, ...args: unknown[]): void;
export declare function normal(prefix: string, ...args: unknown[]): void;
export declare function normalWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function normalWrite(prefix: string, ...args: unknown[]): void;
export declare function normalConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function normalConsole(prefix: string, ...args: unknown[]): void;
export declare function sNormal(prefix: string, filename: string, ...args: unknown[]): string;
export declare function sNormal(prefix: string, ...args: unknown[]): string;
export declare function info(prefix: string, filename: string, ...args: unknown[]): void;
export declare function info(prefix: string, ...args: unknown[]): void;
export declare function infoWrite(prefix: string, filename: string, ...args: unknown[]): void;
export declare function infoWrite(prefix: string, ...args: unknown[]): void;
export declare function infoConsole(prefix: string, filename: string, ...args: unknown[]): void;
export declare function infoConsole(prefix: string, ...args: unknown[]): void;
export declare function sInfo(prefix: string, filename: string, ...args: unknown[]): string;
export declare function sInfo(prefix: string, ...args: unknown[]): string;
//# sourceMappingURL=nodelogger.d.ts.map