import { NodeLoggerConfig } from "../utils/types";
export declare const configNodeLogger: (config: Partial<NodeLoggerConfig>) => void;
export declare const _err: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _err_c: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _err_w: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _err_s: (prefix: string, ...msgs: unknown[]) => string;
export declare const _warn: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _warn_c: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _warn_w: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _warn_s: (prefix: string, ...msgs: unknown[]) => string;
export declare const _normal: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _normal_c: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _normal_w: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _normal_s: (prefix: string, ...msgs: unknown[]) => string;
export declare const _info: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _info_c: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _info_w: (prefix: string, ...msgs: unknown[]) => string | void;
export declare const _info_s: (prefix: string, ...msgs: unknown[]) => string;
//# sourceMappingURL=nodelogger-core.d.ts.map